name       : perl-namespace-clean
version    : 0.27
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RI/RIBASUSHI/namespace-clean-0.27.tar.gz : 8a10a83c3e183dc78f9e7b7aa4d09b47c11fb4e7d3a33b9a12912fd22e31af9d
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Keep imports and functions out of your namespace
description: |
    Keep imports and functions out of your namespace
builddeps  :
    - perl-b-hooks-endofscope
    - perl-package-stash
rundeps    :
    - perl-b-hooks-endofscope
    - perl-package-stash
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
